# run checks on Markdown writing through proselint script:
  # Markdown
  language: ruby

  before_install:
  - gem install mdl

  install:
  - pip install --upgrade pip
  - pip install proselint

  script:
  - proselint README.md
  - mdl README.md
