# Site settings
title: Jonathan Mendez
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Science and Music Major
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mendezjw.com" # the base hostname & protocol for your site
# twitter_username: jonathanwmendez
github_username:  mendezjw

# Build settings
markdown: kramdown
